
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/Masterminds/semver"
  version = "1.4.0"

[[constraint]]
  name = "github.com/docker/docker"
  version = "1.13.1"

[[constraint]]
  name = "github.com/docker/go-connections"
  version = "0.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/michaelbironneau/garbler"

[[constraint]]
  branch = "master"
  name = "github.com/nbutton23/zxcvbn-go"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "gopkg.in/AlecAivazis/survey.v1"
  version = "1.4.0"

[[constraint]]
  name = "gopkg.in/urfave/cli.v1"
  version = "1.20.0"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.0.0-rc15"

[[constraint]]
  branch = "master"
  name = "github.com/google/go-github"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"

[[constraint]]
  name = "gopkg.in/segmentio/analytics-go.v3"
  version = "3.0.0"
