name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      FULL_ACCESS_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup Earthly
        uses: earthly/actions/setup-earthly@v1
        with:
          version: latest
      - name: Run tests
        run: earthly --secret FULL_ACCESS_GITHUB_TOKEN +test
      - name: Build sampctl binaries
        run: earthly +release-all
      - name: Upload Linux binary
        uses: actions/upload-artifact@v6
        with:
          name: sampctl-linux-${{ github.sha }}
          path: sampctl
          retention-days: 30
      - name: Upload Windows binary
        uses: actions/upload-artifact@v6
        with:
          name: sampctl-windows-${{ github.sha }}
          path: sampctl.exe
          retention-days: 30